name: benchmark (ubuntu)
on:
  push:
    branches:
      - benchmark

jobs:
    benchmark:
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash -el {0}
        steps:
            - uses: actions/checkout@v3
            - uses: conda-incubator/setup-miniconda@v2
              with:
                miniforge-variant: Mambaforge
                use-mamba: true
                activate-environment: bocop-dev
                environment-file: pkg/env/bocop-linux-light.yaml
            -  run: python benchmark_bocop.py

