name: CI basic test (mamba)

on: [push, pull_request]

jobs:
    test_examples:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -el {0}
        steps:
            - uses: actions/checkout@v3
            - uses: conda-incubator/setup-miniconda@v2
              with:
                mamba-version: "*"
                channels: conda-forge,defaults
                channel-priority: true
                activate-environment: bocop-dev
                environment-file: pkg/env/bocop-linux.yaml
                auto-activate-base: false
                python-version: 3.7
            -  run: python test_bocop.py 0


# TODO
# add cache (NB. steps from github.org fail, more generally using update on an env activated at conda setup does not work)
# try multi os
# later use pytest and or manual/auto julia tests ?
