name: CI basic test

on: [push, pull_request]

env:
    CACHE_NUMBER: 0

jobs:
    test_examples:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash -el {0}
        steps:
            - uses: actions/checkout@v3

            - name: setup mamba
              uses: conda-incubator/setup-miniconda@v2
              with:
                python-version: 3.7
                mamba-version: "*"
                channels: conda-forge,defaults
                channel-priority: true

            - name: update environment
              run: |
                mamba env update -n bocop-dev -f pkg/env/bocop-linux.yaml
                mamba env create -n bocop-dev2 -f pkg/env/bocop-linux.yaml

            - name: python manual test
              run: |
                conda activate bocop-dev2
                cd bocop/examples/vanderpol
                bash build.sh
                ./bocopApp
                
#python test_bocop.py 0


# TODO
# add cache NB. mambaforge causes an error with cmake...
# try multi os (start with a matrix for linux only)
# later use pytest and or manual/auto julia tests ?
