name: CI basic test
on: [push, pull_request]
jobs:
    test_examples:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: "conda env create -f pkg/env/bocop-linux.yaml; conda activate bocop-dev"
#python test_bocop.py 1
            - run: "cd ./bocop/examples/vanderpol; ls; bash build.sh; bocopApp"
            #- uses: conda-incubator/setup-miniconda@v2
            #  with:
            #    activate-environment: bocop-dev
            #    environment-file: pkg/env/bocop-linux.yaml
            #    python-version: 3.7
            #- name: run manual python test script
            #  run: python test_bocop.py 2


# mamba
# multi os
# later use pytest and or manual/auto julia tests ?
