name: CI basic test (windows)

on: [push, pull_request]

jobs:
    test_examples:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3
            - uses: conda-incubator/setup-miniconda@v2
              with:
                miniforge-variant: Mambaforge
                use-mamba: true
                activate-environment: bocop-dev
                environment-file: pkg/env/bocop-windows.yaml
            #-  run: python test_bocop.py 0

            - run: |
            cd bocop\examples\vanderpol
            dir
            build.bat
            dir
            bocopApp.exe

