name: CI basic test (windows)

on: [push, pull_request]

jobs:
    test_examples:
        runs-on: windows-2019  # windows-latest does not have Visual Studio 16 2019 !
        defaults:
          run:
            shell: bash -el {0}

        steps:
            - uses: actions/checkout@v3
            - uses: ilammy/msvc-dev-cmd@v1 # msvc build tools
            - name: setup conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                miniforge-variant: Mambaforge
                use-mamba: true
                activate-environment: bocop-dev
                environment-file: pkg/env/bocop-windows-light.yaml

            -  run: python test_bocop.py 2

# NB. the cmake command in function build() from bocop.py (l.188) is hardcoded to use Visual Studio 16 2019
# however the windows-latest image uses VS 2022 instead -_-  Use the windows-2019 image.
# The hardcoding of the VS version is still problematic though.

# NB. shell: cmd is required to run .bat file, while shell: bash -el {0} is required for proper env activation -_-
# if possible try to bypass the .bat files completely and use a unified build.py in each problem folder ?