name: CI basic test (windows)

on: [push, pull_request]

jobs:
    test_examples:
        runs-on: windows-latest
        defaults:
            run:
                shell: cmd # required to run .bat file

        steps:
            - uses: actions/checkout@v3
            - uses: ilammy/msvc-dev-cmd@v1 # msvc build tools
            #- uses: microsoft/setup-msbuild@v1.3 
            - uses: conda-incubator/setup-miniconda@v2
              with:
                miniforge-variant: Mambaforge
                use-mamba: true
                activate-environment: bocop-dev
                environment-file: pkg/env/bocop-windows-light.yaml
            #-  run: python test_bocop.py 0

            - run: conda activate bocop-dev
            - run: cd bocop\examples\vanderpol
            - run: build.bat
            - run: dir
            - run: bocopApp.exe
              

