name: CI (windows)
on:
#  push:
#    branches:
#      - main
  pull_request:

jobs:
    test_examples:
        runs-on: windows-2019
        defaults:
          run:
            shell: bash -el {0}
        steps:
            - uses: actions/checkout@v3
            - uses: ilammy/msvc-dev-cmd@v1 # msvc build tools
            - uses: conda-incubator/setup-miniconda@v2
              with:
                miniforge-variant: Mambaforge
                use-mamba: true
                activate-environment: bocop-dev
                environment-file: pkg/env/bocop-windows-light.yaml
            -  run: python test_bocop.py 2

