name: CI basic test (windows)

on: [push, pull_request]

jobs:
    test_examples:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3
            - uses: ilammy/msvc-dev-cmd@v1
            - uses: microsoft/setup-msbuild@v1.3 
            - uses: conda-incubator/setup-miniconda@v2
              with:
                miniforge-variant: Mambaforge
                use-mamba: true
                activate-environment: bocop-dev
                environment-file: pkg/env/bocop-windows.yaml
            #-  run: python test_bocop.py 0

            - run: |
                conda env list
                conda list
                conda activate bocop-dev
                cd bocop\examples\vanderpol
                build.bat
                dir
                bocopApp.exe
              shell: cmd

