name: CI basic test (windows)

on: [push, pull_request]

jobs:
    test_examples:
        runs-on: windows-latest
        defaults:
          run:
            shell: bash -el {0}

        steps:
            - uses: actions/checkout@v3
            - uses: ilammy/msvc-dev-cmd@v1 # msvc build tools
            - name: setup conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                miniforge-variant: Mambaforge
                use-mamba: true
                activate-environment: bocop-dev
                environment-file: pkg/env/bocop-windows-light.yaml

            -  run: python test_bocop.py 2  # try this anyway, does not use bat file...

# NB. shell: cmd is required to run .bat file, while shell: bash -el {0} is required for proper env activation -_-
# if possible try to bypass the .bat files completely and use a unified build.py in each problem folder ?