name: CI basic test (windows)

on: [push, pull_request]

jobs:
    test_examples:
        runs-on: windows-latest
        defaults:
          run:
            shell: bash -el {0}

        steps:
            - uses: actions/checkout@v3
            - uses: ilammy/msvc-dev-cmd@v1 # msvc build tools
            #- uses: microsoft/setup-msbuild@v1.3 # needed ?
            - name: setup conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                miniforge-variant: Mambaforge
                use-mamba: true
                activate-environment: bocop-dev
                environment-file: pkg/env/bocop-windows-light.yaml

            #- run: conda activate bocop-dev  # env does not seem to be activated cf above ?

            #- name: build bocopApp
            #  working-directory: .\bocop\examples\vanderpol
            #  run: build.bat
            #  shell: cmd # required to run .bat file
            #- name: run bocopApp
            #  working-directory: .\bocop\examples\vanderpol 
            #  run: bocopApp.exe

            -  run: python test_bocop.py 0  # try this anyway, does not use bat file...